SELECT 

[ProductKey], 
[ProductAlternateKey], 
--[ProductSubcategoryKey], 
--[WeightUnitMeasureCode], 
--[SizeUnitMeasureCode], 
[EnglishProductName],
ps.EnglishProductSubcategoryName as sub_category,
pc.EnglishProductCategoryName as product_category,
--[SpanishProductName], 
--[FrenchProductName], 
--[StandardCost], 
--[FinishedGoodsFlag], 
[Color], 
--[SafetyStockLevel],
--[ReorderPoint], 
--[ListPrice], 
[Size], 
--[SizeRange], 
--[Weight], 
--[DaysToManufacture], 
[ProductLine], 
--[DealerPrice], 
--[Class], 
--[Style], 
[ModelName], 
--[LargePhoto], 
[EnglishDescription], 
--[FrenchDescription], 
--[ChineseDescription], 
--[ArabicDescription], 
--[HebrewDescription], 
--[ThaiDescription], 
--[GermanDescription],
--[JapaneseDescription], 
--[TurkishDescription],
--[StartDate], 
--[EndDate],
[Status],
ISNULL(p.Status,'OutDated') as product_status
FROM DimProduct as p
LEFT JOIN DimProductSubcategory as ps ON ps.ProductSubcategoryKey=p.ProductSubcategoryKey
LEFT JOIN DimProductCategory as pc ON pc.ProductCategoryKey=pc.ProductCategoryKey
ORDER BY p.ProductKey asc