SELECT [CustomerKey] , 
--[GeographyKey], 
--[CustomerAlternateKey],
--[Title],
[FirstName],
--[MiddleName],
[LastName],
c.FirstName+' '+LastName as full_name,
--[NameStyle],
--[BirthDate],
--[MaritalStatus], 
--[Suffix],
CASE c.Gender WHEN 'M' THEN 'MALE' WHEN 'F' THEN 'FEMALE' END AS Gender_,
--[Gender],
--[EmailAddress],
--[YearlyIncome], 
--[TotalChildren], 
--[NumberChildrenAtHome],
--[EnglishEducation],
--[SpanishEducation], 
--[FrenchEducation],
--[EnglishOccupation], 
--[SpanishOccupation],
--[FrenchOccupation],
--[HouseOwnerFlag],
--[NumberCarsOwned],
--[AddressLine1],
--[AddressLine2],
--[Phone],
--[DateFirstPurchase], 
--[CommuteDistance],
c.DateFirstPurchase as Datefirstpurchase,
g.City AS customer_city
FROM DimCustomer as c
LEFT JOIN DimGeography AS g ON g.GeographyKey=c.GeographyKey
ORDER BY CustomerKey asc